config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  devise_for :users
  resources  :users,        only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources  :microposts,    only: [:create, :destroy] do
    resources  :comments,    only: [:create, :destroy]
    resources  :likes,       only: [:create, :destroy]
  end
  resources  :comments do
    resources  :comments,    only: [:create, :destroy]
  end
  resources  :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost,                    optional: true
  belongs_to :parent,  class_name: Comment, optional: true
  has_many   :replies, class_name: Comment,
             foreign_key: :parent_id,
             dependent: :destroy
  validates :user_id, presence: true
  validates :content, presence: true, length: { minimum: 5, maximum: 150}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :user_signed_in?, only: [:create, :edit, :destroy]
  before_action :correct_user,    only: :destroy
  before_action :find_commentable

  def create
    @comment = params[:micropost_id] ? @commentable.comments.create(comment_params)
                                     : @commentable.replies.create(comment_params)

    # Add user directly to comment
    @comment.user = current_user

    # if @comment.save
    #   flash[:success] = "Comment created."
    #   redirect_to request.referer || root_path
    # else
    #   redirect_to request.referer || root_path
    # end

    respond_to do |format|
      if @comment.save
        format.html { redirect_to request.referer || root_path, notice: "Comment created." }
        format.js
      else
        format.html { redirect_to request.referer || root_path }
      end
    end
  end


  def destroy
    @comment = Comment.find(params[:id]).destroy
    flash[:success] = "Comment removed."
    redirect_to request.referer || root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to root_path if @comment.nil?
  end

  def find_commentable
    @commentable = params[:micropost_id] ? Micropost.find(params[:micropost_id])
                                         : Comment.find(params[:comment_id])
  end
end

app/views/comments/_comment.html.erb
<div class="well">
  <ul>
    <li>
      <strong><%= comment.user.name %></strong> says:
      <%= comment.content %>
      <div>
        <%= link_to "Delete Comment", [comment.micropost, comment],
                                      remote: true,
                                      method: :delete,
                                      data: { confirm: "Are u sure?" } %>
      </div>

      <%= form_for(Comment.new, url: comment_comments_path(comment), remote: true) do |f| %>
        <%= f.text_area :content, placeholder: "Reply...." %>
        <%= f.submit "Reply", class: "btn btn-primary btn-sm"%>
      <% end %>

      <ul>
        <%= render partial: 'comments/comment', collection: comment.replies %>
      </ul>
    </li>
  </ul>
</div>

app/views/comments/_form.html.erb
<%= form_for([micropost, Comment.new], remote: true) do |f| %>
  <div class="form-group">
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_area :content, placeholder: 'Comment....' %>
  </div>
  <%= f.submit "Add Comment", class: "btn btn-primary btn-sm" %>
<% end %>

app/views/comments/create.js.erb
$('#comment').append('<%= escape_javascript(render @comment) %>');