config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  devise_for :users
  resources  :users,        only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources  :microposts,    only: [:create, :destroy] do
    resources  :comments,    only: [:create, :destroy]
    resources  :likes,       only: [:create, :destroy]
  end
  resources  :comments do
    resources  :comments,    only: [:create, :destroy]
  end
  resources  :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @micropost = Micropost.find(params[:micropost_id])
    @like = @micropost.likes.create(user_id: current_user.id)
    respond_to do |format|
      format.html
      format.js { render action: "toggle" }
    end
  end

  def destroy
    like = Like.find(params[:id])
    @micropost = like.micropost
    like.destroy
    respond_to do |format|
      format.html
      format.js { render action: "toggle" }
    end
  end
end

app/views/likes/_like_button.html.erb
<% if like = current_user.likes.find_by(micropost_id: micropost.id) %>
  <%= form_for [like.micropost, like], method: :delete, remote: true do |f| %>
    <%= f.hidden_field :micropost_id %>
    <%= f.hidden_field :user_id %>
    <%= f.submit "Liked", class: "btn btn-primary" %>
  <% end %>
<% else %>
  <%= form_for Like.new, url: micropost_likes_path(micropost.id), remote: true do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :micropost_id %>
    <%= f.submit "Like", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/likes/toggle.js.erb
$("#like").html("<%= escape_javascript(render ('like_button'), micropost: @micropost) %>");
$("#like-stats").html("<strong><%= pluralize(@micropost.likes.count, 'user') %></strong> like this")